apiVersion: v1
kind: Service
metadata:
  name: chat-service-node
  labels:
    app: chat-service-node
spec:
  type: NodePort
  selector:
    app: chat-service-node
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
